//
//  ViewConstants.m
//  ConcurMobile
//
//  Created by Paul Kramer on 2/5/10.
//  Copyright 2010 Concur. All rights reserved.
//

#import "ViewConstants.h"


@implementation ViewConstants

NSString * const SEG_TYPE_HOTEL = @"HOTEL";
NSString * const SEG_TYPE_AIR = @"AIR";
NSString * const SEG_TYPE_RIDE = @"RIDE";
NSString * const SEG_TYPE_DINING = @"DINING";
NSString * const SEG_TYPE_EVENT = @"EVENT";
NSString * const SEG_TYPE_RAIL = @"RAIL";
NSString * const SEG_TYPE_CAR = @"CAR";
NSString * const SEG_TYPE_PARKING = @"PARKING";
NSString * const SEG_TYPE_UNDEFINED = @"UNDEFINED";

NSString * const TO_VIEW = @"TO_VIEW";
NSString * const TRIP_KEY = @"TRIP_KEY";
NSString * const TRIP = @"TRIP";
NSString * const TRIP_DETAILS_TEXT = @"Trip Details";
NSString * const BOOK_TAXI = @"BOOK_TAXI";
NSString * const SEGMENT_LIST_VIEW = @"SEGMENT_LIST_VIEW";

NSString * const HOME_PAGE = @"HOME_PAGE";
NSString * const LOGIN = @"LOGIN";
NSString * const REGISTER = @"REGISTER";
NSString * const PWD_LOGIN = @"PWD_LOGIN";
NSString * const INFO = @"INFO";
NSString * const ENTRIES = @"ENTRIES";
NSString * const TRIPS = @"TRIPS";
NSString * const SPLASH = @"SPLASH";
NSString * const TRIP_DETAILS = @"TRIP_DETAILS";
NSString * const RECEIPT_DETAILS = @"RECEIPT_DETAILS";
NSString * const RECEIPT_DETAIL_VIEW = @"RECEIPT_DETAIL_VIEW";
NSString * const ITIN_DETAILS = @"ITIN_DETAILS";
NSString * const MAP = @"MAP";
NSString * const SOUTHWEST = @"SOUTHWEST";
NSString * const WEBVIEW = @"WEBVIEW";
NSString * const SETTINGS_VIEW = @"SETTINGS_VIEW";
NSString * const HOME_PAGE_BREEZE = @"HOME_PAGE_BREEZE";
NSString * const OUT_OF_POCKET_LIST = @"OUT_OF_POCKET_LIST";
NSString * const OUT_OF_POCKET_FORM = @"OUT_OF_POCKET_FORM";
NSString * const LOGIN_OPTIONS_VIEW = @"LOGIN_OPTIONS_VIEW";
NSString * const CORP_SSO_VIEW = @"CORP_SSO_VIEW";
NSString * const EXPENSE_TYPES_LIST = @"EXPENSE_TYPES_LIST";
NSString * const EXPENSE_LOCATIONS_LIST = @"EXPENSE_LOCATIONS_LIST";

NSString * const APPROVE_REPORTS = @"APPROVE_REPORTS";
NSString * const APPROVE_ENTRIES = @"APPROVE_ENTRIES";
NSString * const APPROVE_EXPENSE_DETAILS = @"APPROVE_EXPENSE_DETAILS";
NSString * const EXPENSE_RECEIPT_MANAGER = @"EXPENSE_RECEIPT_MANAGER";
NSString * const APPROVE_REPORT_SUMMARY = @"APPROVE_REPORT_SUMMARY";
NSString * const APPROVE_VIEW_EXCEPTIONS = @"APPROVE_VIEW_EXCEPTIONS";
NSString * const APPROVE_VIEW_COMMENTS = @"APPROVE_VIEW_COMMENTS";
NSString * const APPROVE_VIEW_ITEMIZATIONS = @"APPROVE_VIEW_ITEMIZATIONS";
NSString * const APPROVE_VIEW_ATTENDEES = @"APPROVE_VIEW_ATTENDEES";
NSString * const APPROVE_VIEW_AND_EDIT_ATTENDEES = @"APPROVE_VIEW_AND_EDIT_ATTENDEES";
NSString * const RECEIPT_MANAGER = @"RECEIPT_MANAGER";
NSString * const RECEIPT_MANAGER_SELECTOR = @"RECEIPT_MANAGER_SELECTOR";
NSString * const RECEIPT_MANAGER_IMAGES = @"RECEIPT_MANAGER_IMAGES";
NSString * const AUTHENTICATION_VIEW = @"AUTHENTICATION_VIEW";
NSString * const ITEMIZATION_LIST = @"ITEMIZATION_LIST";
NSString * const PC_TRANSACTION = @"PC_TRANSACTION";

NSString * const SELECT_REPORT = @"SELECT_REPORT";
NSString * const ACTIVE_REPORTS = @"ACTIVE_REPORTS";
NSString * const TRAVEL_REQUESTS = @"TRAVEL_REQUESTS";
NSString * const TRAVEL_AGENCY_INFO = @"TRAVEL_AGENCY_INFORMATION";
NSString * const ACTIVE_ENTRIES = @"ACTIVE_ENTRIES";

NSString * const ITIN_DETAILS_AIR = @"ITIN_DETAILS_AIR";
NSString * const ITIN_DETAILS_HOTEL = @"ITIN_DETAILS_HOTEL";
NSString * const ITIN_DETAILS_CAR = @"ITIN_DETAILS_CAR";
NSString * const ITIN_DETAILS_DINING = @"ITIN_DETAILS_DINING";
NSString * const ITIN_DETAILS_RIDE = @"ITIN_DETAILS_RIDE";
NSString * const ITIN_DETAILS_EVENT = @"ITIN_DETAILS_EVENT";
NSString * const ITIN_DETAILS_RAIL = @"ITIN_DETAILS_RAIL";
NSString * const ITIN_DETAILS_PARKING = @"ITIN_DETAILS_PARKING";
NSString * const ITIN_DETAILS_UNDEFINED = @"ITIN_DETAILS_UNDEFINED";

NSString * const HOTEL = @"HOTEL";
NSString * const DISTANCE = @"DISTANCE";
NSString * const HOTEL_LOCATION = @"HOTEL_LOCATION";
NSString * const HOTEL_TEXT_EDITOR = @"HOTEL_TEXT_EDITOR";
NSString * const HOTEL_DATES = @"HOTEL_DATES";
NSString * const HOTEL_OPTIONS = @"HOTEL_OPTIONS";
NSString * const HOTEL_SEARCH_RESULTS = @"HOTEL_SEARCH_RESULTS";
NSString * const HOTEL_ROOM_LIST = @"HOTEL_ROOM_LIST";
NSString * const HOTEL_DETAILS = @"HOTEL_DETAILS";
NSString * const HOTEL_DETAILED_MAP = @"HOTEL_DETAILED_MAP";
NSString * const HOTEL_BOOKING = @"HOTEL_BOOKING";
NSString * const HOTEL_CREDIT_CARD = @"HOTEL_CREDIT_CARD";
NSString * const HOTEL_VIOLATIONS = @"HOTEL_VIOLATIONS";

NSString * const CAR = @"CAR";
NSString * const CAR_DATES = @"CAR_DATES";
NSString * const CAR_LIST = @"CAR_LIST";
NSString * const CAR_DETAILS = @"CAR_DETAILS";
NSString * const CAR_MAP = @"CAR_MAP";

NSString * const TRAIN_BOOK = @"TRAIN_BOOK";

NSString * const APPROVE_INVOICES=@"APPROVE_INVOICES";
NSString * const INVOICE_LINEITEMS=@"INVOICE_LINEITEMS";
NSString * const INVOICE_LINEITEM_DETAIL=@"INVOICE_LINEITEM_DETAIL";
NSString * const INVOICE_SUMMARY=@"INVOICE_SUMMARY";
NSString * const INVOICE_VENDOR=@"INVOICE_VENDOR";
NSString * const INVOICE_RECEIPT=@"INVOICE_RECEIPT";

NSString * const ATTENDEE_ENTRY = @"ATTENDEE_ENTRY";
NSString * const TEXT_FIELD_EDIT = @"TEXT_FIELD_EDIT";
NSString * const FORM_EDIT = @"FORM_EDIT";
NSString * const MODAL_OPTIONS =@"MODAL_OPTIONS";

// Home page constants
NSString * const SCREEN_NAME = @"HOME_PAGE";
NSString * const LABEL_TRIPS = @"LABEL_TRIPS";
NSString * const LABEL_EXPENSES = @"LABEL_EXPENSES";
NSString * const LABEL_SETTINGS = @"LABEL_SETTINGS";
NSString * const LABEL_HOTELS = @"LABEL_HOTELS";
NSString * const LABEL_CAR_RENTAL = @"LABEL_CAR_RENTAL";
NSString * const LABEL_TAXI = @"LABEL_TAXI";
NSString * const LABEL_AIR = @"LABEL_AIR";
NSString * const LABEL_APPROVE_EXPENSES = @"LABEL_APPROVE_EXPENSES";
NSString * const LABEL_QUICK_EXPENSE = @"LABEL_QUICK_EXPENSE";
NSString * const LABEL_TRAVEL = @"LABEL_TRAVEL";
NSString * const LABEL_EXPENSE = @"LABEL_EXPENSE";
NSString * const RECEIPT_STORE_VIEWER = @"RECEIPT_STORE_VIEWER";
NSString * const RECEIPT_STORE_DETAIL_VIEW = @"RECEIPT_STORE_DETAIL_VIEW";
NSString * const REPORT_DETAIL = @"REPORT_DETAIL";
NSString * const QUICK_EXPENSES_AND_RECEIPTS_COMBO_VIEW = @"QUICK_EXPENSES_AND_RECEIPTS_COMBO_VIEW";

NSString * const LOCATION_CHECK_IN = @"LOCATION_CHECK_IN";

NSString * const SEARCH_YODLEE_CARDS = @"SEARCH_YODLEE_CARDS";
NSString * const ADD_YODLEE_CARD = @"ADD_YODLEE_CARD";

NSString * const TRIPIT_AUTH = @"TRIPIT_AUTH";

NSString * const GOV_QUICK_EXPENSE = @"GOV_QUICK_EXPENSE";
NSString * const GOV_EXPENSE_TYPES = @"GOV_EXPENSE_TYPES";

NSString * const LOGIN_HELP_TOPIC = @"LOGIN_HELP_TOPIC";

NSString * const UPLOAD_QUEUE_VIEW_CONTROLLER = @"UPLOAD_QUEUE_VIEW_CONTROLLER";

@end
